export { default as firstimg } from "assets/firstimg.png"
export { default as secondimg } from "assets/secondimg.png"
export { default as thirdimg } from "assets/thirdimg.png"
export { default as arrow } from "assets/arrow.png"
export { default as forthimg } from "assets/forthimg.png"
export { default as bluredqrcode } from "assets/bluredqrcode.png"
export { default as arrow2 } from "assets/arrow2.png"
export { default as phone } from "assets/phone.png"